#SET LANGUAGE
ALTER SCHEMA DEFAULT CHARACTER SET latin1  DEFAULT COLLATE latin1_spanish_ci ;


#JOURNAL TABLE
CREATE TABLE IF NOT EXISTS JOURNAL (
  ID int NOT NULL AUTO_INCREMENT,
  SERVICE_NAME VARCHAR(255) DEFAULT NULL,
  STARTED_ON TIMESTAMP(6) DEFAULT NULL,
  FINISHED_ON TIMESTAMP(6) DEFAULT NULL,
  OPERATION_ID VARCHAR(255) DEFAULT NULL,
  CORRELATION_ID VARCHAR(255) DEFAULT NULL,
  SUCCEEDED BOOLEAN DEFAULT NULL,
  REASON_CODE INT DEFAULT NULL,
  REASON VARCHAR(255),
  MESSAGES TEXT,
  PRIMARY KEY (ID),
  UNIQUE KEY IX_OPERATION (OPERATION_ID),
  KEY IX_CORRELATION (CORRELATION_ID),
  KEY IX_SERVICE_DATES (STARTED_ON,SERVICE_NAME)
);

#LONG RUNNING BATCH TABLE
CREATE TABLE LONG_RUNNING_BATCH (
  ID                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  OPERATION_ID        VARCHAR(255) NOT NULL,
  CORRELATION_ID      VARCHAR(255) DEFAULT NULL,
  SERVICE_NAME        VARCHAR(255) DEFAULT NULL,
  SERVICE_STATUS      INT NOT NULL,
  STARTED_ON          TIMESTAMP(6) NOT NULL,
  FINISHED_ON         TIMESTAMP(6) DEFAULT NULL,
  SUCCEEDED           BOOLEAN DEFAULT NULL,
  REASON              VARCHAR(255) DEFAULT NULL,
  REASON_CODE         INT DEFAULT NULL,
  CHILDREN_COUNT      INT NOT NULL,
  COMPLETED_OK        INT DEFAULT 0,
  COMPLETED_ERR       INT DEFAULT 0,
  LAST_UPDATED        DATETIME NOT NULL
);

CREATE INDEX IDX_CORRELATION_ID ON LONG_RUNNING_BATCH(CORRELATION_ID);
CREATE INDEX IDX_OPERATION_ID ON LONG_RUNNING_BATCH(OPERATION_ID);